version: "3"
services:
  api:
    build: ./backend
    container_name: api
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/home/node/app/api
  react-ui:
    build: ./frontend/
    container_name: react-ui
    command: yarn dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/home/node/app/frontend
